# Generated by Django 3.2.6 on 2021-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('mentoring_subject', models.TextField()),
                ('status', models.CharField(choices=[('ong', '요청 중'), ('act', '요청 수락'), ('cle', '요청 취소'), ('rej', '요청 거절')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MentoringTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('mentoring_subject', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ini', '멘토링 가능'), ('ong', '멘토링 진행 중'), ('cpt', '멘토링 완료'), ('unc', '멘토링 미완료')], max_length=5)),
            ],
        ),
    ]
