# Generated by Django 3.2.6 on 2021-10-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringtimetable',
            name='after_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentoringtimetable',
            name='before_memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
